// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYOdvqchg7y01MPsGlQfP0cFPv60BF0U0',
    appId: '1:543615060106:web:4aaa329df35df51c54c573',
    messagingSenderId: '543615060106',
    projectId: 'notification-flutter-123',
    authDomain: 'notification-flutter-123.firebaseapp.com',
    storageBucket: 'notification-flutter-123.appspot.com',
    measurementId: 'G-720N27TH2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYDidGVFy9lSL0woBMcrTyVvbzGV_DDlk',
    appId: '1:543615060106:android:5d1d6952c9eece2c54c573',
    messagingSenderId: '543615060106',
    projectId: 'notification-flutter-123',
    storageBucket: 'notification-flutter-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEJgRn1YGlQC0owbxQVwbBd6cYmQbH65w',
    appId: '1:543615060106:ios:4770e298437fd59c54c573',
    messagingSenderId: '543615060106',
    projectId: 'notification-flutter-123',
    storageBucket: 'notification-flutter-123.appspot.com',
    iosClientId: '543615060106-rnoec8h0c2aimn5cvp36v2n73n6bkbbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );
}
